#!/usr/bin/env python3
import os
import sys
import json
import re
import argparse
from pathlib import Path

SYSTEM_PROMPT = """
You are LORE's Epistemic Engine.
Your task is not to describe "what the code does", but to extract the TRUE Business Intent (the "why"),
reconcile its evolution over time, identify exceptions and technical debt, and structure it into a computable Knowledge Graph Node.

Input:
You will receive the complete or partial Git History of a file, in Markdown format.

Reasoning Instructions (Mandatory pre-JSON):
Before generating the final output, open a `<thinking>` block where you analyze:
1. Evolution: What was the original intent? Was it silently weakened or reinforced over time?
2. Implicit Assumptions: Are there undocumented bypasses?
3. Health (Integrity Score): How reliable is this rule today compared to when it was born?

Output Formatter:
After the thinking block, return EXCLUSIVELY a valid JSON object matching the established schema (keys: intent_id, version, type, title, intent_health, canonical_intent, current_binding, evolution_log, active_exceptions, guard_rules, source).
"""

def extract_json_from_response(llm_response: str) -> dict:
    start_idx = llm_response.find("{")
    if start_idx == -1:
        raise ValueError("No valid JSON found.")
    bracket_count = 0
    in_string = False
    escape_char = False
    quote_char = None
    for i in range(start_idx, len(llm_response)):
        char = llm_response[i]
        if escape_char:
            escape_char = False
            continue
        if char == "\\":
            escape_char = True
            continue
        if char in ('"', "'"):
            if not in_string:
                in_string = True
                quote_char = char
            elif char == quote_char:
                in_string = False
                quote_char = None
            continue
        if not in_string:
            if char == "{":
                bracket_count += 1
            elif char == "}":
                bracket_count -= 1
                if bracket_count == 0:
                    json_str = llm_response[start_idx:i+1]
                    try:
                        return json.loads(json_str)
                    except json.JSONDecodeError as e:
                        print(f"[error] Invalid JSON: {e}", file=sys.stderr)
                        raise
    match = re.search(r'\{.*\}', llm_response, re.DOTALL)
    if not match:
        raise ValueError("No valid JSON found.")
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError as e:
        print(f"[error] Invalid JSON in fallback: {e}", file=sys.stderr)
        raise

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("history_file", help="Path to the .md file generated by the historian")
    parser.add_argument("--output-dir", default=".lore/nodes", help="JSON destination folder")
    args = parser.parse_args()

    history_path = Path(args.history_file)
    if not history_path.exists():
        sys.exit(f"[error] File not found: {history_path}")

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Initialize LLM Client
    try:
        from core.llm_client import get_llm_client
        client = get_llm_client(Path.cwd())
    except Exception as e:
        sys.exit(f"[error] Failed to initialize LLM client: {e}")
    content = history_path.read_text(encoding="utf-8")

    print("[info] Invoking Claude 3.5 Sonnet (Reconciler)...", file=sys.stderr)
    
    try:
        response = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=8192,
            temperature=0.1,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": content}]
        )
        raw_text = response.content[0].text
    except Exception as e:
        sys.exit(f"[error] Anthropic API failed: {e}")

    try:
        intent_node = extract_json_from_response(raw_text)
    except Exception:
        print(raw_text, file=sys.stderr)
        sys.exit(1)

    intent_id = intent_node.get("intent_id", "UNKNOWN-INTENT-ID")
    # Sanitize intent_id to prevent path traversal (Bug 19)
    intent_id = Path(intent_id).name.replace("..", "").replace("/", "").replace("\\", "")
    output_path = out_dir / f"{intent_id}.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(intent_node, f, indent=2, ensure_ascii=False)

    print(f"\n[success] Node saved to: {output_path}")
    print(f"  Health: {intent_node.get('intent_health', {}).get('status')} (Score: {intent_node.get('intent_health', {}).get('integrity_score')})")

if __name__ == "__main__":
    main()